# This is a basic workflow to help you get started with Actions

name: Checkmarx AST Scan on Push + Publish Results into Security Alerts Dashboard

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  scan_and_publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          base_uri: https://anz.ast.checkmarx.net/
          cx_tenant: cx_apac_se_michael_pogrebisky
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          additional_params: --sast-preset-name "Checkmarx Default" --report-format sarif --output-name results
          
      - name: Publish SARIF File
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
